project_id = "irvrmkshjcyabjubihmp"

[functions.client-manifest]
verify_jwt = false

[functions.bdr-book]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false
[functions.process-email-queue]
verify_jwt = true

[functions.seo-generate-plan]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-daily-room]
verify_jwt = false
